title: Stackbit Fresh Theme
baseurl: /
permalink: '/:title/'
collections:
  posts:
    permalink: '/posts/:title/'
layout_style: overflow
palette: blue
header:
  title: Mac Siri
  tagline: >-
    I'm a refactor-loving developer and I promise you I have nothing to do with
    Apple's Siri.
  profile_img: >-
    https://res.cloudinary.com/practicaldev/image/fetch/s--YR1oKjpM--/c_fill,f_auto,fl_progressive,h_320,q_auto,w_320/https://thepracticaldev.s3.amazonaws.com/uploads/user/profile_image/560/a2fed92f-a747-41f7-953c-28da1ade0e95.jpeg
  bg: dark
  has_nav: true
  has_social: true
footer:
  content: '&copy; All rights reserved.'
  links:
    - text: Made with Stackbit
      url: 'https://www.stackbit.com'
      new_window: true
sass:
  indentWidth: 4
  style: nested
  precision: 10
plugins:
  - jekyll-menus
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - ssg-build.sh
  - LICENSE.md
  - README.md
  - netlify.toml
  - stackbit-build.sh
  - stackbit-pull.js
